"""menukar tipe data lokasi_toko pada table user dari string menjadi TEXT

Revision ID: 05183f24b685
Revises: 754824f3c669
Create Date: 2018-07-31 15:13:23.787535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05183f24b685'
down_revision = '754824f3c669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
