"""menukar tipe data lokasi_toko dan nomor telepon pada table user dari string menjadi VARCHAR

Revision ID: 0fb04b8fa83d
Revises: 493d292da054
Create Date: 2018-07-31 15:19:50.373332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb04b8fa83d'
down_revision = '493d292da054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
