"""inisialisasi database

Revision ID: 368a5c2a8572
Revises: 
Create Date: 2018-07-07 13:37:34.240246

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '368a5c2a8572'
down_revision = None
branch_labels = None
depends_on = None
status_pembayaran = ENUM('pending', 'confirmed', 'rejected', name='status_pembayaran', create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembeli',
    sa.Column('kode_pembeli', sa.String(), nullable=False),
    sa.Column('nama_pembeli', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.Numeric(), nullable=True),
    sa.Column('alamat_pembeli', sa.String(), nullable=True),
    sa.Column('nama_ikan_yang_dipesan', sa.String(), nullable=True),
    sa.Column('jumlah_pesanan', sa.String(), nullable=True),
    sa.Column('harga_total_pesanan', sa.Integer(), nullable=True),
    sa.Column('tanggal_pemesanan', sa.DateTime(), nullable=True),
    sa.Column('ikan_id', sa.Integer(), nullable=False),
    sa.Column('status_pembayaran', status_pembayaran, nullable=True),
    sa.ForeignKeyConstraint(['ikan_id'], ['ikan.id_ikan'], ),
    sa.PrimaryKeyConstraint('kode_pembeli'),
    sa.UniqueConstraint('kode_pembeli')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    # ### end Alembic commands ###
