"""menukar tipe data lokasi_toko dan nomor telepon pada table user dari string menjadi TEXT

Revision ID: 493d292da054
Revises: 05183f24b685
Create Date: 2018-07-31 15:17:13.222944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493d292da054'
down_revision = '05183f24b685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['nama_toko'])
    op.create_unique_constraint(None, 'user', ['lokasi_penjualan'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
