"""testing kolom domsili dengan string

Revision ID: 4fde10414001
Revises: bbcdc2d9ad3e
Create Date: 2018-08-18 13:43:49.093332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fde10414001'
down_revision = 'bbcdc2d9ad3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penjual', sa.Column('domisili', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penjual', 'domisili')
    # ### end Alembic commands ###
