"""reset

Revision ID: 5275d8f1d2ef
Revises: 
Create Date: 2018-08-03 04:39:01.885876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5275d8f1d2ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
