"""menambah kolom nomor telepon pada table user

Revision ID: 707a87eadcac
Revises: c80ad7ec0f7a
Create Date: 2018-07-31 14:53:41.476212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707a87eadcac'
down_revision = 'c80ad7ec0f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikan', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ikan', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('nomor_telepon', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['nomor_telepon'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'nomor_telepon')
    op.drop_constraint(None, 'ikan', type_='foreignkey')
    op.drop_column('ikan', 'user_id')
    # ### end Alembic commands ###
