"""inisialisasi database

Revision ID: 72c712719082
Revises: 
Create Date: 2018-07-07 08:07:25.511919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c712719082'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembeli',
    sa.Column('nomor_pembeli', sa.Integer(), nullable=False),
    sa.Column('nama_pembeli', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.Numeric(), nullable=True),
    sa.Column('alamat_pembeli', sa.String(), nullable=True),
    sa.Column('nama_ikan_yang_dipesan', sa.String(), nullable=True),
    sa.Column('jumlah_pesanan', sa.String(), nullable=True),
    sa.Column('harga_total_pesanan', sa.Integer(), nullable=True),
    sa.Column('tanggal_pemesanan', sa.DateTime(), nullable=True),
    sa.Column('ikan_id', sa.Integer(), nullable=False),
    sa.Column('status_pembayaran', sa.Enum('pending', 'confirmed', 'rejected', name='status_pembayaran'), nullable=True),
    sa.ForeignKeyConstraint(['ikan_id'], ['ikan.id_ikan'], ),
    sa.PrimaryKeyConstraint('nomor_pembeli'),
    sa.UniqueConstraint('nomor_pembeli')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    # ### end Alembic commands ###
