"""inisialisasi database

Revision ID: 7404816eb00a
Revises: 
Create Date: 2018-06-18 01:24:10.861567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7404816eb00a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ikan',
    sa.Column('id_ikan', sa.Integer(), nullable=False),
    sa.Column('nama_ikan', sa.String(), nullable=True),
    sa.Column('ukuran', sa.Integer(), nullable=True),
    sa.Column('minimal_order', sa.Integer(), nullable=True),
    sa.Column('ketersediaan', sa.Enum('tersedia', 'stock habis', name='Ketersediaan'), nullable=True),
    sa.Column('kondisi', sa.Enum('frozen', 'segar', name='kondisi ikan'), nullable=True),
    sa.PrimaryKeyConstraint('id_ikan')
    )
    op.create_table('pembeli',
    sa.Column('nomor_pembeli', sa.Integer(), nullable=False),
    sa.Column('nama_pembeli', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.Numeric(), nullable=True),
    sa.Column('alamat_pembeli', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nomor_pembeli'),
    sa.UniqueConstraint('nomor_pembeli')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    op.drop_table('ikan')
    # ### end Alembic commands ###
