"""menukar nama kolom lokasi toko menjadi lokasi_penjualan

Revision ID: 754824f3c669
Revises: 707a87eadcac
Create Date: 2018-07-31 14:56:17.703109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754824f3c669'
down_revision = '707a87eadcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lokasi_penjualan', sa.String(), nullable=True))
    op.drop_column('user', 'lokasi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lokasi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'lokasi_penjualan')
    # ### end Alembic commands ###
