"""menukar nama table user dengan table penjual dan menghapus kolom kondisi_ikan pada table ikan


Revision ID: 7a01658dd81c
Revises: b94546b39758
Create Date: 2018-08-03 03:17:24.264427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a01658dd81c'
down_revision = 'b94546b39758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_toko', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nomor_telepon', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('domisili', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domisili'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nama_toko'),
    sa.UniqueConstraint('nomor_telepon')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['penjual.id'], )
    )
    op.create_foreign_key(None, 'ikan', 'penjual', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'pembeli', ['kode_pembeli'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pembeli', type_='unique')
    op.drop_constraint(None, 'ikan', type_='foreignkey')
    op.drop_table('roles_users')
    op.drop_table('role')
    op.drop_table('penjual')
    # ### end Alembic commands ###
