"""menambahkan table domisili dan relasi dengan table penjual dan membuat form dosmili berdasrarkan value yang diambil dari kolom domisili

Revision ID: af2637a590a1
Revises: 
Create Date: 2018-08-18 09:08:12.201023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2637a590a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penjual', sa.Column('domisili_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'penjual', 'domisili', ['domisili_id'], ['id_domisili'])
    op.drop_column('penjual', 'domisili')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penjual', sa.Column('domisili', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'penjual', type_='foreignkey')
    op.drop_column('penjual', 'domisili_id')
    # ### end Alembic commands ###
