"""menukar nama table user dengan table penjual dan menghapus kolom kondisi_ikan pada table ikan


Revision ID: b94546b39758
Revises: 6a15cfa2fa66
Create Date: 2018-08-03 02:59:50.506890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = 'b94546b39758'
down_revision = '6a15cfa2fa66'
branch_labels = None
depends_on = None


status_pembayaran = ENUM('pending', 'confirmed', 'rejected', name='status_pembayaran', create_type=False)
ketersediaan = ENUM('tersedia', 'stock habis', name='Ketersediaan', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_toko', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nomor_telepon', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('domisili', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domisili'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nama_toko'),
    sa.UniqueConstraint('nomor_telepon')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ikan',
    sa.Column('id_ikan', sa.Integer(), nullable=False),
    sa.Column('nama_ikan', sa.String(), nullable=True),
    sa.Column('keterangan_ikan', sa.String(), nullable=True),
    sa.Column('berat_ikan_dalam_Kg', sa.Integer(), nullable=True),
    sa.Column('minimal_order_dalam_Kg', sa.Integer(), nullable=True),
    sa.Column('harga_per_Kg', sa.Integer(), nullable=True),
    sa.Column('foto_ikan', sa.Unicode(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
                    sa.Column('ketersediaan', ketersediaan, nullable=True),
    sa.Column('urutan_ikan_dalam_tampilan_halaman', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['penjual.id'], ),
    sa.PrimaryKeyConstraint('id_ikan')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['penjual.id'], )
    )
    op.create_table('pembeli',
    sa.Column('kode_pembeli', sa.String(), nullable=False),
    sa.Column('nama_pembeli', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.String(), nullable=True),
    sa.Column('alamat_pembeli', sa.String(), nullable=True),
    sa.Column('nama_ikan_yang_dipesan', sa.String(), nullable=True),
    sa.Column('jumlah_pesanan', sa.String(), nullable=True),
    sa.Column('harga_total_pesanan', sa.Integer(), nullable=True),
    sa.Column('tanggal_pemesanan', sa.DateTime(), nullable=True),
    sa.Column('ikan_id', sa.Integer(), nullable=False),
                    sa.Column('status_pembayaran', status_pembayaran, nullable=True),
    sa.ForeignKeyConstraint(['ikan_id'], ['ikan.id_ikan'], ),
    sa.PrimaryKeyConstraint('kode_pembeli'),
    sa.UniqueConstraint('kode_pembeli')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    op.drop_table('roles_users')
    op.drop_table('ikan')
    op.drop_table('role')
    op.drop_table('penjual')
    # ### end Alembic commands ###
