"""kolom domisili tidak pakai relationship, jadi domsili di inputkan secara manual dengan ketik

Revision ID: b9c30d1511f2
Revises: 4fde10414001
Create Date: 2018-08-18 14:13:18.653373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c30d1511f2'
down_revision = '4fde10414001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
