"""testing tukar kolom domisili dengan string

Revision ID: bbcdc2d9ad3e
Revises: af2637a590a1
Create Date: 2018-08-18 11:16:29.913660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcdc2d9ad3e'
down_revision = 'af2637a590a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penjual', sa.Column('domisili', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penjual', 'domisili')
    # ### end Alembic commands ###
