"""inisialisasi database

Revision ID: bc7a3cb3e484
Revises: 
Create Date: 2018-07-05 06:30:06.812011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'bc7a3cb3e484'
down_revision = None
branch_labels = None
depends_on = None

ketersediaan = ENUM('tersedia', 'stock habis', name='Ketersediaan', create_type=False)
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ikan',
    sa.Column('id_ikan', sa.Integer(), nullable=False),
    sa.Column('nama_ikan', sa.String(), nullable=True),
    sa.Column('keterangan_ikan', sa.String(), nullable=True),
    sa.Column('berat_ikan_dalam_Kg', sa.Integer(), nullable=True),
    sa.Column('minimal_order_dalam_Kg', sa.Integer(), nullable=True),
    sa.Column('harga_per_Kg', sa.Integer(), nullable=True),
    sa.Column('foto_ikan', sa.Unicode(length=128), nullable=True),
    sa.Column('ketersediaan', ketersediaan, nullable=True),
    sa.Column('kondisi_ikan', sa.Enum('frozen', 'segar', name='kondisi_ikan'), nullable=True),
    sa.Column('urutan_ikan_dalam_tampilan_halaman', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_ikan')
    )
    op.create_table('pembeli',
    sa.Column('nomor_pembeli', sa.Integer(), nullable=False),
    sa.Column('nama_pembeli', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.Numeric(), nullable=True),
    sa.Column('alamat_pembeli', sa.String(), nullable=True),
    sa.Column('nama_ikan_yang_dipesan', sa.String(), nullable=True),
    sa.Column('jumlah_pesanan', sa.String(), nullable=True),
    sa.Column('harga_total_pesanan', sa.Integer(), nullable=True),
    sa.Column('tanggal_pemesanan', sa.DateTime(), nullable=True),
    sa.Column('ikan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['ikan_id'], ['ikan.id_ikan'], ),
    sa.PrimaryKeyConstraint('nomor_pembeli'),
    sa.UniqueConstraint('nomor_pembeli')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    op.drop_table('ikan')
    # ### end Alembic commands ###
