"""menukar tipe data nomor telepon pada table pembeli dari numeric menjadi string

Revision ID: c80ad7ec0f7a
Revises: e1a07a7bf97d
Create Date: 2018-07-31 14:16:57.497123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80ad7ec0f7a'
down_revision = 'e1a07a7bf97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
