"""adding kolumn is public

Revision ID: c93038308271
Revises: 0fb04b8fa83d
Create Date: 2018-07-31 15:47:42.054737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93038308271'
down_revision = '0fb04b8fa83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikan', sa.Column('is_public', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ikan', 'is_public')
    # ### end Alembic commands ###
