"""inisialisasi database

Revision ID: d37f7e0fc30a
Revises: 
Create Date: 2018-06-20 04:24:44.249957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37f7e0fc30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikan', sa.Column('berat_ikan_dalam_Kg', sa.Integer(), nullable=True))
    op.add_column('ikan', sa.Column('foto_ikan', sa.Unicode(length=128), nullable=True))
    op.drop_column('ikan', 'ukuran_dalam_Kg')
    op.drop_column('ikan', 'room_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ikan', sa.Column('room_images', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('ikan', sa.Column('ukuran_dalam_Kg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ikan', 'foto_ikan')
    op.drop_column('ikan', 'berat_ikan_dalam_Kg')
    # ### end Alembic commands ###
