"""menambahkan kolom lokasi pada table user dan menghapus kolom last_name dan pada kolom first name ditukar menjadi nama_toko

Revision ID: e1a07a7bf97d
Revises: 6504672864a4
Create Date: 2018-07-31 10:42:39.414823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a07a7bf97d'
down_revision = '6504672864a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lokasi', sa.String(), nullable=True))
    op.add_column('user', sa.Column('nama_toko', sa.String(length=255), nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user', 'nama_toko')
    op.drop_column('user', 'lokasi')
    # ### end Alembic commands ###
