"""menukar kolom lokasi dengan domisili pada table user

Revision ID: fd6fce480b2d
Revises: c93038308271
Create Date: 2018-08-01 11:30:06.376114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6fce480b2d'
down_revision = 'c93038308271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ikan', 'is_public',
               existing_type=sa.BOOLEAN(),
               )
    op.add_column('user', sa.Column('domisili', sa.VARCHAR(), nullable=True))
    op.drop_constraint('user_lokasi_penjualan_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['domisili'])
    op.drop_column('user', 'lokasi_penjualan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lokasi_penjualan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_lokasi_penjualan_key', 'user', ['lokasi_penjualan'])
    op.drop_column('user', 'domisili')
    op.alter_column('ikan', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
